const dataProvincias = {
    Bagua: ["Aramango", "Copallin", "El Parco", "Imaza", "La Peca"],
    Bongará: [
        "Jumbilla",
        "Chisquilla",
        "Churuja",
        "Corosha",
        "Cuispes",
        "Florida",
        "Jazán",
        "Recta",
        "San Carlos",
        "Shipasbamba",
        "Valera",
        "Yambrasbamba",
    ],
    Chachapoyas: [
        "Asunción",
        "Balsas",
        "Cheto",
        "Chiliquin",
        "Chuquibamba",
        "Granada",
        "Huancas",
        "La Jalca",
        "Leimebamba",
        "Levanto",
        "Magdalena",
        "Mariscal Castilla",
        "Molinopampa",
        "Montevideo",
        "Olleros",
        "Quinjalca",
        "San Francisco de Daguas",
        "San Isidro de Maino",
        "Soloco",
        "Sonche",
    ],
    Condorcanqui: ["El Cenepa", "Nieva", "Río Santiago"],
    Luya: [
        "Lamud",
        "Camporredondo",
        "Cocabamba",
        "Colcamar",
        "Conila",
        "Inguilpata",
        "Longuita",
        "Lonya Chico",
        "Luya",
        "Luya Viejo",
        "María",
        "Ocalli",
        "Ocumal",
        "Pisuquia",
        "Providencia",
        "San Cristóbal",
        "San Francisco de Yesoíca",
        "San Jerónimo",
        "San Juan de Lopecancha",
        "Santa Catalina",
        "Santo Tomás",
        "Tingo",
        "Trita",
    ],
    "Rodríguez de Mendoza": [
        "San Nicolás",
        "Chirimoto",
        "Cochamal",
        "Huambo",
        "Limabamba",
        "Longar",
        "Mariscal Benavides",
        "Milpuc",
        "Omia",
        "Santa Rosa",
        "Totora",
        "Vista Alegre",
    ],
    Utcubamba: [
        "Bagua Grande",
        "Cajaruro",
        "Cumba",
        "El Milagro",
        "Jamalca",
        "Lonya Grande",
        "Yamon",
    ],
    Aija: ["Aija", "Coris", "Huacllán", "La Merced", "Succha"],
    "Antonio Raymondi": [
        "Llamellin",
        "Aczo",
        "Chaccho",
        "Chingas",
        "Mirgas",
        "San Juan de Rontoy",
    ],
    Asunción: ["Chacas", "Acochaca"],
    Bolognesi: ["Huallanca", "Ancash", "La Primavera", "Quiches"],
    Carhuaz: [
        "Carhuaz",
        "Acopampa",
        "Amashca",
        "Anta",
        "Ataquero",
        "Marcara",
        "Pariahuanca",
        "San Miguel de Aco",
        "Shilla",
        "Tinco",
    ],
    "Carlos Fermín Fitzcarrald": [
        "San Luis",
        "San Nicolás",
        "Yauya",
        "Casma",
        "Buena Vista Alta",
        "Comandante Noel",
    ],
    Casma: ["Casma", "Buena Vista Alta", "Comandante Noel"],
    Corongo: ["Corongo", "Aco", "Bambas", "Cusca", "La Pampa", "Yanac"],
    Huaraz: [
        "Huaraz",
        "Cochabamba",
        "Colcabamba",
        "Huanchay",
        "Independencia",
        "Jangas",
        "La Libertad",
        "Olleros",
        "Pampas Grande",
        "Pariacoto",
        "Pira",
        "Tarica",
    ],
    Huari: [
        "Huari",
        "Anra",
        "Cajay",
        "Chavin de Huantar",
        "Huacachi",
        "Huacchis",
        "Huachis",
        "Huantar",
        "Masin",
        "Paucas",
        "Ponto",
        "Rahuapampa",
        "Rapayan",
        "San Marcos",
        "San Pedro de Chana",
        "Uco",
    ],
    Huarmey: ["Huarmey", "Cochapeti", "Culebras", "Huayan", "Malvas"],
    Huaylas: [
        "Caraz",
        "Huallanca",
        "Huata",
        "Huaylas",
        "Mato",
        "Pamparomas",
        "Pueblo Libre",
        "Santa Cruz",
        "Santo Toribio",
        "Yuracmarca",
    ],
    "Mariscal Luzuriaga": [
        "Piscobamba",
        "Casca",
        "Eleazar Guzmán Barrón",
        "Fidel Olivas Escudero",
        "Llama",
        "Llumpa",
        "Lucma",
        "Musga",
    ],
    Ocros: [
        "Ocros",
        "Acas",
        "Cajamarquilla",
        "Cochas",
        "Congas",
        "Llipa",
        "San Cristóbal de Rajan",
        "San Pedro",
    ],
    Pallasca: [
        "Cabana",
        "Bolognesi",
        "Conchucos",
        "Huacaschuque",
        "Huandoval",
        "Lacabamba",
        "Llapo",
        "Pallasca",
        "Pampas",
        "Santa Rosa",
        "Tauca",
    ],
    Pomabamba: [
        "Pomabamba",
        "Huayllan",
        "Parobamba",
        "Quinuabamba",
        "Tayabamba",
    ],
    Recuay: [
        "Recuay",
        "Catac",
        "Cotaparaco",
        "Huayllapampa",
        "Llacllin",
        "Marca",
        "Pampas Chico",
        "Pararin",
        "Tapacocha",
        "Ticapampa",
    ],
    Santa: [
        "Chimbote",
        "Cáceres del Perú",
        "Coishco",
        "Macate",
        "Moro",
        "Nepeña",
        "Samanco",
        "Santa",
    ],
    Sihuas: [
        "Sihuas",
        "Acobamba",
        "Alfonso Ugarte",
        "Cashapampa",
        "Chingalpo",
        "Huayllabamba",
        "Quiches",
        "Ragash",
        "San Juan",
        "Sicsibamba",
    ],
    Yungay: [
        "Yungay",
        "Cascapara",
        "Mancos",
        "Matacoto",
        "Quillo",
        "Ranrahirca",
        "Shupluy",
        "Yanama",
    ],
    Abancay: [
        "Abancay",
        "Chacoche",
        "Circa",
        "Curahuasi",
        "Huanipaca",
        "Lambrama",
        "Pichirhua",
        "San Pedro de Cachora",
    ],
    Andahuaylas: [
        "Andahuaylas",
        "Andarapa",
        "Chiara",
        "Huancarama",
        "Huancaray",
        "Kishuara",
        "Pacobamba",
        "Pacucha",
        "Pampachiri",
        "San Antonio de Cachi",
    ],
    Antabamba: [
        "Antabamba",
        "El Oro",
        "Huaquirca",
        "Juan Espinoza Medrano",
        "Oropesa",
    ],
    Aymaraes: [
        "Chalhuanca",
        "Capaya",
        "Caraybamba",
        "Chapimarca",
        "Colcabamba",
        "Cotaruse",
        "Ihuayllo",
        "Justo Apu Sahuaraura",
        "Lucre",
        "Pocohuanca",
        "San Juan de Chacña",
        "Saño",
    ],
    Cotabambas: [
        "Tambobamba",
        "Cotabambas",
        "Coyllurqui",
        "Haquira",
        "Mara",
        "Challhuahuacho",
    ],
    Chincheros: [
        "Chincheros",
        "Anco-Huallo",
        "Cocharcas",
        "Huaccana",
        "Ocobamba",
        "Ongoy",
        "Uranmarca",
        "Ranracancha",
    ],
    Grau: [
        "Chuquibambilla",
        "Curpahuasi",
        "Grau",
        "Huayllati",
        "Mamara",
        "Micaela Bastidas",
        "Pataypampa",
        "Progreso",
        "San Antonio",
        "Santa Rosa",
        "Turpay",
    ],
    Arequipa: [
        "Arequipa",
        "Alto Selva Alegre",
        "Cayma",
        "Cerro Colorado",
        "Characato",
        "Chiguata",
        "Jacobo Hunter",
        "La Joya",
        "Mariano Melgar",
        "Miraflores",
        "Mollebaya",
        "Paucarpata",
        "Pocsi",
        "Polobaya",
        "Quequeña",
        "Sabandía",
        "Sachaca",
        "San Juan de Siguas",
        "San Juan de Tarucani",
        "Santa Isabel de Siguas",
        "Santa Rita de Siguas",
        "Socabaya",
        "Tiabaya",
        "Uchumayo",
        "Vitor",
        "Yanahuara",
        "Yarabamba",
        "Yura",
    ],
    Camaná: [
        "Camaná",
        "José María Quimper",
        "Mariano Nicolás Valcárcel",
        "Mariscal Cáceres",
        "Nicolás de Piérola",
        "Ocoña",
        "Quilca",
        "Samuel Pastor",
    ],
    Caravelí: [
        "Caravelí",
        "Acari",
        "Atico",
        "Atiquipa",
        "Bella Unión",
        "Cahuacho",
        "Chala",
        "Chaparra",
        "Huanuhuanu",
        "Jaqui",
        "Lomas",
        "Quicacha",
        "Yauca",
    ],
    Castilla: [
        "Aplao",
        "Andagua",
        "Ayo",
        "Chachas",
        "Chilcaymarca",
        "Choco",
        "Huancarqui",
        "Machaguay",
        "Orcopampa",
        "Pampacolca",
        "Tipan",
        "Uñon",
        "Uraca",
        "Viraco",
    ],
    Caylloma: [
        "Chivay",
        "Achoma",
        "Cabanaconde",
        "Callalli",
        "Caylloma",
        "Coporaque",
        "Huambo",
        "Huanca",
        "Ichupampa",
        "Lari",
        "Lluta",
        "Maca",
        "Madrigal",
        "San Antonio de Chuca",
        "Sibayo",
        "Tapay",
        "Tisco",
        "Tuti",
        "Yanque",
    ],
    Condesuyos: [
        "Chuquibamba",
        "Andaray",
        "Cayarani",
        "Chichas",
        "Iray",
        "Río Grande",
        "Salamanca",
        "Yanaquihua",
    ],
    Islay: [
        "Mollendo",
        "Cocachacra",
        "Dean Valdivia",
        "Islay",
        "Mejía",
        "Punta de Bombón",
    ],
    "La Unión": [
        "Cotahuasi",
        "Alca",
        "Charcana",
        "Huaynacotas",
        "Pampamarca",
        "Puyca",
        "Quechualla",
        "Sayla",
        "Tauria",
        "Tomepampa",
        "Toro",
    ],
    Cangallo: [
        "Cangallo",
        "Chuschi",
        "Los Morochucos",
        "María Parado de Bellido",
        "Paras",
    ],
    Huamanga: [
        "Ayacucho",
        "Acocro",
        "Carmen Alto",
        "Chiara",
        "Jesús Nazareno",
        "Ocros",
        "Pacaycasa",
        "Quinua",
        "San José de Ticllas",
        "San Juan Bautista",
        "Santiago de Pischa",
        "Socos",
        "Tambo",
        "Vinchos",
        "Los Molinos",
    ],
    "Huanca Sancos": [
        "Sancos",
        "Carapo",
        "Sacsamarca",
        "Santiago de Lucanamarca",
    ],
    Huanta: [
        "Huanta",
        "Ayahuanco",
        "Huamanguilla",
        "Iguain",
        "Luricocha",
        "Santillana",
        "Sivia",
        "San Miguel",
    ],
    "La Mar": [
        "San Miguel",
        "Anco",
        "Ayna",
        "Chilcas",
        "Chungui",
        "Luis Carranza",
        "Santa Rosa",
        "Tambo",
        "Samugari",
        "Anchihuay",
    ],
    Lucanas: [
        "Puquio",
        "Aucara",
        "Cabana",
        "Carmen Salcedo",
        "Chaviña",
        "Chipao",
        "Huac-Huas",
        "Laramate",
        "Leoncio Prado",
        "Llauta",
        "Lucanas",
        "Ocaña",
        "Otoca",
        "Saisa",
        "San Cristóbal",
        "San Juan",
        "San Pedro",
        "San Pedro de Palco",
        "Sancos",
        "Santa Ana de Huaycahuacho",
        "Santa Lucía",
    ],
    Parinacochas: [
        "Coracora",
        "Chumpi",
        "Coronel Castañeda",
        "Pacapausa",
        "Pullo",
        "Puyusca",
        "San Francisco de Ravacayco",
        "Upahuacho",
    ],
    "Páucar del Sara Sara": [
        "Pausa",
        "Colta",
        "Corculla",
        "Lampa",
        "Marcabamba",
        "Oyolo",
        "Pararca",
        "San Javier de Alpabamba",
        "San José de Ushua",
        "Sara Sara",
    ],
    Sucre: [
        "Querobamba",
        "Belen",
        "Chalcos",
        "Chilcayoc",
        "Huacaña",
        "Morcolla",
        "Paico",
        "San Pedro de Larcay",
        "San Salvador de Quije",
        "Santiago de Paucaray",
    ],
    "Víctor Fajardo": [
        "Huancapi",
        "Alcamenca",
        "Apongo",
        "Asquipata",
        "Canaria",
    ],
    Huancapi: [
        "Huancapi",
        "Alcamenca",
        "Apongo",
        "Asquipata",
        "Canaria",
        "Cayara",
        "Colca",
        "Huamanquiquia",
        "Huancaraylla",
        "Huaya",
        "Sarhua",
        "Vilcanchos",
    ],
    "Vilcas Huamán": [
        "Vilcas Huamán",
        "Accomarca",
        "Carhuanca",
        "Concepción",
        "Huambalpa",
        "Independencia",
        "Saurama",
        "Vischongo",
    ],
    Cajabamba: ["Cajabamba", "Cachachi", "Condebamba", "Sitacocha"],
    Cajamarca: [
        "Cajamarca",
        "Asunción",
        "Chetilla",
        "Cospan",
        "Encañada",
        "Jesus",
        "Llacanora",
        "Los Baños del Inca",
        "Magdalena",
        "Matara",
        "Namora",
        "San Juan",
        "Cumbemayo",
    ],
    Celendín: [
        "Celendín",
        "Chumuch",
        "Cortegana",
        "Huasmin",
        "Jorge Chávez",
        "José Gálvez",
        "Miguel Iglesias",
        "Oxamarca",
        "Sorochuco",
        "Sucre",
        "Utco",
    ],
    Chota: [
        "Chota",
        "Anguia",
        "Chadin",
        "Chalamarca",
        "Chiguirip",
        "Chimban",
        "Choropampa",
        "Cochabamba",
        "Conchan",
        "Huambos",
        "Lajas",
        "Llama",
        "Miracosta",
        "Paccha",
        "Pion",
        "Querocoto",
        "San Juan de Licupis",
        "Tacabamba",
        "Tocmoche",
        "Chalamarca",
    ],
    Contumazá: [
        "Contumazá",
        "Chilete",
        "Cupisnique",
        "Guzmango",
        "San Benito",
        "Santa Cruz de Toledo",
        "Tantarica",
        "Yonán",
    ],
    Cutervo: [
        "Cutervo",
        "Callayuc",
        "Choros",
        "Cujillo",
        "La Ramada",
        "Pimpingos",
        "Querocotillo",
        "San Andrés de Cutervo",
        "San Juan de Cutervo",
        "San Luis de Lucma",
        "Santa Cruz",
        "Santo Domingo de la Capilla",
        "Santo Tomás",
        "Socota",
        "Toribio Casanova",
        "Uticyacu",
    ],
    Hualgayoc: ["Bambamarca", "Chugur", "Hualgayoc"],
    Jaén: [
        "Jaén",
        "Bellavista",
        "Chontali",
        "Colasay",
        "Huabal",
        "Las Pirias",
        "Pomahuaca",
        "Pucara",
        "Sallique",
        "San Felipe",
        "San José del Alto",
        "Santa Rosa",
        "Santiago",
        "Son Máncer",
        "Soritor",
        "Yambrasbamba",
    ],
    "San Ignacio": [
        "San Ignacio",
        "Chirinos",
        "Huarango",
        "La Coipa",
        "Namballe",
        "San José de Lourdes",
        "Tabaconas",
    ],
    "San Marcos": [
        "Pedro Gálvez",
        "Chancay",
        "Eduardo Villanueva",
        "Gregorio Pita",
        "Ichocán",
        "José Manuel Quiroz",
        "José Sabogal",
        "Pedro Gálvez",
        "San Antonio",
        "San Luis",
        "Santa Cruz de Toledo",
        "Yambrasbamba",
    ],
    "San Miguel": [
        "San Miguel",
        "Bolívar",
        "Calquis",
        "Catilluc",
        "El Prado",
        "La Florida",
        "Llapa",
        "Nanchoc",
        "Niepos",
        "San Gregorio",
        "Tantara",
        "Unión Agua Blanca",
        "Yamón",
    ],
    "San Pablo": ["San Pablo", "San Bernardino", "San Luis", "Tumbaden"],
    "Santa Cruz": [
        "Santa Cruz",
        "Andabamba",
        "Catache",
        "Chancaybaños",
        "La Esperanza",
        "Ninabamba",
        "Pulan",
        "Saucepampa",
        "Sexi",
        "Uticyacu",
        "Yauyucan",
    ],
    Callao: [
        "Callao",
        "Bellavista",
        "Carmen de la Legua Reynoso",
        "La Perla",
        "La Punta",
        "Ventanilla",
    ],
    Acomayo: [
        "Acomayo",
        "Acopia",
        "Acos",
        "Mosoc Llacta",
        "Pomacanchi",
        "Rondocan",
        "Sangarará",
    ],
    Anta: [
        "Anta",
        "Ancahuasi",
        "Cachimayo",
        "Chinchaypujio",
        "Huarocondo",
        "Limatambo",
        "Mollepata",
        "Pucyura",
        "Zurite",
    ],
    Calca: [
        "Calca",
        "Coya",
        "Lamay",
        "Lares",
        "Pisac",
        "San Salvador",
        "Taray",
        "Yanatile",
    ],
    Canas: [
        "Yanaoca",
        "Checca",
        "Kunturkanki",
        "Langui",
        "Layo",
        "Pampamarca",
        "Quehue",
        "Tupac Amaru",
    ],
    Canchis: [
        "Sicuani",
        "Checacupe",
        "Combapata",
        "Marangani",
        "Pitumarca",
        "San Pablo",
        "San Pedro",
        "Tinta",
    ],
    Chumbivilcas: [
        "Santo Tomás",
        "Capacmarca",
        "Chamaca",
        "Colquemarca",
        "Livitaca",
        "Llusco",
        "Quiñota",
        "Velille",
    ],
    Cusco: [
        "Cusco",
        "Ccorca",
        "Poroy",
        "San Jerónimo",
        "San Sebastián",
        "Santiago",
        "Saylla",
        "Wanchaq",
    ],
    Espinar: [
        "Yauri",
        "Condoroma",
        "Coporaque",
        "Espinar",
        "Ocoruro",
        "Pallpata",
        "Pichigua",
        "Suyckutambo",
    ],
    "La Convención": [
        "Quillabamba",
        "Echarati",
        "Huayopata",
        "Maranura",
        "Ocobamba",
        "Santa Ana",
        "Santa Teresa",
        "Vilcabamba",
        "Kimbasbamba",
        "Pichari",
        "Sacramento",
        "San Francisco",
        "San José",
        "San Martín",
        "Ayna",
        "Ayna San Francisco",
        "San Miguel",
        "Santa Rosa",
        "Vraem",
    ],
    Paruro: [
        "Paruro",
        "Accha",
        "Ccapacmarca",
        "Colcha",
        "Huanoquite",
        "Omacha",
        "Paccaritambo",
        "Pillpinto",
        "Yaurisque",
    ],
    Paucartambo: [
        "Paucartambo",
        "Caicay",
        "Challabamba",
        "Colquepata",
        "Huancarani",
        "Kosñipata",
        "Paucartambo",
        "San Francisco",
        "San Pedro",
    ],
    Quispicanchi: [
        "Urcos",
        "Andahuaylillas",
        "Camanti",
        "Ccarhuayo",
        "Ccatca",
        "Cusipata",
        "Huaro",
        "Lucre",
        "Marcapata",
        "Ocongate",
        "Oropesa",
        "Quiquijana",
        "Urcos",
    ],
    Urubamba: [
        "Urubamba",
        "Chinchero",
        "Huayllabamba",
        "Machupicchu",
        "Maras",
        "Ollantaytambo",
        "Yucay",
    ],
    Acobamba: [
        "Acobamba",
        "Andabamba",
        "Anta",
        "Caja",
        "Marcas",
        "Paucará",
        "Pomacocha",
        "Rosario",
    ],
    Angaraes: [
        "Lircay",
        "Anchonga",
        "Callanmarca",
        "Ccochaccasa",
        "Chincho",
        "Congalla",
        "Huanca-Huanca",
        "Huayllay Grande",
        "Julcamarca",
        "San Antonio de Antaparco",
        "Santo Tomas de Pata",
    ],
    Castrovirreyna: [
        "Castrovirreyna",
        "Arma",
        "Aurahua",
        "Capillas",
        "Chupamarca",
        "Cocas",
        "Huachos",
        "Huamatambo",
        "Mollepampa",
        "San Juan",
        "Santa Ana",
        "Tantara",
        "Ticrapo",
    ],
    Churcampa: [
        "Churcampa",
        "Anco",
        "Chinchihuasi",
        "El Carmen",
        "La Merced",
        "Locroja",
        "Paucarbamba",
        "San Miguel de Mayocc",
        "San Pedro de Coris",
        "Pachamarca",
        "Cosme",
    ],
    Huancavelica: [
        "Huancavelica",
        "Acobambilla",
        "Acoria",
        "Conayca",
        "Cuenca",
        "Huachocolpa",
        "Huayllahuara",
        "Izcuchaca",
        "Laria",
        "Manta",
        "Mariscál Cáceres",
        "Moya",
        "Nuevo Occoro",
        "Palca",
        "Pilchaca",
        "Vilca",
        "Yauli",
    ],
    Huaytará: [
        "Huaytará",
        "Ayavi",
        "Córdova",
        "Huayacundo Arma",
        "Huaytara",
        "Laramarca",
        "Ocoyo",
        "Pilpichaca",
        "Querco",
        "Quito-Arma",
        "San Antonio de Cusicancha",
        "San Francisco de Sangayaico",
        "San Isidro",
        "Santiago de Chocorvos",
        "Santiago de Quirahuara",
        "Santo Domingo de Capillas",
        "Tambo",
    ],
    Tayacaja: [
        "Pampas",
        "Acostambo",
        "Acraquia",
        "Ahuaycha",
        "Colcabamba",
        "Daniel Hernández",
        "Huachocolpa",
        "Huaribamba",
        "Ñahuimpuquio",
        "Pazos",
        "Quishuar",
        "Salcabamba",
        "Salcahuasi",
        "San Marcos de Rocchac",
        "Surcubamba",
        "Tintay Puncu",
    ],
    Ambo: ["Ambo", "Cayna", "Colpas", "Conchamarca", "Huacar", "San Francisco"],
    "Dos de Mayo": [
        "La Unión",
        "Chuquis",
        "Marías",
        "Pachas",
        "Quivilla",
        "Ripán",
        "Shunqui",
        "Sillapata",
        "Yanas",
    ],
    Huacaybamba: ["Huacaybamba", "Canchabamba", "Cochabamba", "Pinra"],
    Huamalíes: [
        "Llata",
        "Arancay",
        "Chavín de Pariarca",
        "Jacas Grande",
        "Jircán",
        "Miraflores",
        "Monzón",
        "Punchao",
        "Puños",
        "Singa",
        "Tantamayo",
    ],
    Huánuco: [
        "Huanuco",
        "Amarilis",
        "Chinchao",
        "Churubamba",
        "Margos",
        "Quisqui",
        "San Francisco de Cayrán",
        "San Pedro de Chaulán",
        "Santa María del Valle",
        "Yarumayo",
    ],
    "La Marr": [
        "Ayna",
        "Chuahua",
        "Churcampa",
        "Locro",
        "Maucau",
        "Paca",
        "Puerto Inca",
        "Samugari",
        "Uchiza",
        "Tingo María",
    ],
    "Leoncio Prado": [
        "Tingo María",
        "Rupa-Rupa",
        "Daniel Alomía Robles",
        "Hermilio Valdizán",
        "José Crespo y Castillo",
        "Luyando",
        "Mariano Dámaso Beraun",
        "Pucayacu",
        "Castillo Grande",
    ],
    Marañón: ["Huacrachuco", "Cholon", "San Buenaventura", "La Morada"],
    Pachitea: ["Panao", "Chaglla", "Molino", "Umari"],
    "Puerto Inca": [
        "Puerto Inca",
        "Codo del Pozuzo",
        "Honoria",
        "Tournavista",
        "Yuyapichis",
    ],
    Lauricocha: [
        "Jesús",
        "Baños",
        "Jivia",
        "Queropalca",
        "Rondos",
        "San Francisco de Asís",
        "San Miguel de Cauri",
    ],
    Yarowilca: [
        "Chavinillo",
        "Cahuac",
        "Chacabamba",
        "Chupán",
        "Jacas Chico",
        "Obas",
        "Pampamarca",
        "Choras",
        "Sánchez Carrión",
        "San Daniel",
        "San Juan de Licupis",
        "Yacus",
    ],
    Chincha: [
        "Chincha Alta",
        "Alto Larán",
        "Chavín",
        "Chincha Baja",
        "El Carmen",
        "Grocio Prado",
        "Pueblo Nuevo",
        "San Juan de Yanac",
        "San Pedro de Huacarpana",
        "Sunampe",
        "Tambo de Mora",
    ],
    Ica: [
        "Ica",
        "La Tinguiña",
        "Los Aquijes",
        "Ocucaje",
        "Pachacútec",
        "Parcona",
        "Pueblo Nuevo",
        "Salas",
        "San José de Los Molinos",
        "San Juan Bautista",
        "Santiago",
    ],
    Nasca: ["Nasca", "Changuillo", "El Ingenio", "Marcona", "Vista Alegre"],
    Palpa: ["Palpa", "Llipata", "Río Grande", "Santa Cruz", "Tibillo"],
    Pisco: [
        "Pisco",
        "Huancano",
        "Humay",
        "Independencia",
        "Paracas",
        "San Andrés",
        "San Clemente",
        "Tupac Amaru Inca",
    ],
    Chanchamayo: [
        "La Merced",
        "Ahuania",
        "Chanchamayo",
        "Pichanaki",
        "Puentes",
        "San Luis de Shuaro",
        "San Ramón",
        "Vitoc",
    ],
    Chupaca: [
        "Chupaca",
        "Ahuac",
        "Chongos Bajo",
        "Huachac",
        "Huamancaca Chico",
        "San Juan de Jarpa",
        "Yanacancha",
        "San Juan de Jarpa",
        "Yanacancha",
    ],
    Concepción: [
        "Concepción",
        "Aco",
        "Andamarca",
        "Chambara",
        "Cochas",
        "Comas",
        "Heroinas Toledo",
        "Manzanares",
        "Mariscal Castilla",
        "Matahuasi",
        "Mito",
        "Nueve de Julio",
        "Orcotuna",
        "San José de Quero",
        "Santa Rosa de Ocopa",
    ],
    Huancayo: [
        "Huancayo",
        "Carhuacallanga",
        "Chacapampa",
        "Chicche",
        "Chilca",
        "Chongos Alto",
        "Chupuro",
        "Colca",
        "Cullhuas",
        "El Tambo",
        "Huacrapuquio",
        "Hualhuas",
        "Huamancaca",
        "Huancan",
        "Huancayo",
        "Huasicancha",
        "Huayucachi",
        "Ingenio",
        "Pariahuanca",
        "Pilcomayo",
        "Pucara",
        "Quichuay",
        "Quilcas",
        "San Agustín",
        "San Jerónimo de Tunán",
        "San Lorenzo",
        "San Pedro de Saño",
        "Santo Domingo de Acobamba",
        "Sapallanga",
        "Sicaya",
        "Viques",
    ],
    Jauja: [
        "Jauja",
        "Acolla",
        "Apata",
        "Ataura",
        "Canchayllo",
        "Curicaca",
        "El Mantaro",
        "Huamali",
        "Huaripampa",
        "Huertas",
        "Janjaillo",
        "Julcán",
        "Leonor Ordóñez",
        "Llocllapampa",
        "Marco",
        "Masma",
        "Masma Chicche",
        "Molinos",
        "Monobamba",
        "Muqui",
        "Muquiyauyo",
        "Paca",
        "Paccha",
        "Pancan",
        "Parco",
        "Pomacancha",
        "Ricran",
        "San Lorenzo",
        "San Pedro de Chunan",
        "Sausa",
        "Sincos",
        "Tunanmarca",
        "Yauli",
    ],
    Junín: ["Junín", "Carhuamayo", "Ondores", "Ulcumayo"],
    Satipo: [
        "Satipo",
        "Coviriali",
        "Llaylla",
        "Mazamari",
        "Pampa Hermosa",
        "Pangoa",
        "Río Negro",
        "Río Tambo",
        "Vizcatán del Ene",
    ],
    Tarma: [
        "Tarma",
        "Acobamba",
        "Huaricolca",
        "Huasahuasi",
        "La Unión",
        "Palca",
        "Palcamayo",
        "San Pedro de Cajas",
        "Tapo",
    ],
    Yauli: [
        "La Oroya",
        "Chacapalpa",
        "Huay-Huay",
        "Marcapomacocha",
        "Morococha",
        "Paccha",
        "Santa Bárbara de Carhuacayan",
        "Santa Rosa de Sacco",
        "Suitucancha",
        "Yauli",
    ],
    "La Oroya": [
        "La Oroya",
        "Chacapalpa",
        "Huay-Huay",
        "Marcapomacocha",
        "Morococha",
        "Paccha",
        "Santa Bárbara de Carhuacayan",
        "Santa Rosa de Sacco",
        "Suitucancha",
        "Yauli",
    ],
    Yanahuanca: [
        "Yanahuanca",
        "Chacayán",
        "Goyllarisquizga",
        "Paucar",
        "San Pedro de Pillao",
        "Santa Ana de Tusi",
        "Tapuc",
        "Vilcabamba",
        "Villicabamba",
        "Vitoc",
    ],
    Ascope: [
        "Ascope",
        "Casa Grande",
        "Chicama",
        "Chocope",
        "Magdalena de Cao",
        "Paiján",
        "Rázuri",
        "Santiago de Cao",
    ],
    Bolívar: [
        "Bolívar",
        "Bambamarca",
        "Condormarca",
        "Longotea",
        "Uchumarca",
        "Ucuncha",
    ],
    Chepén: ["Chepén", "Pacanga", "Pueblo Nuevo"],
    "Gran Chimú": ["Cascas", "Lucma", "Marmot", "Sayapullo"],
    Julcán: ["Julcán", "Calamarca", "Carabamba", "Huaso"],
    Otuzco: [
        "Otuzco",
        "Agallpampa",
        "Charat",
        "Huaranchal",
        "La Cuesta",
        "Mache",
        "Paranday",
        "Salpo",
        "Sinsicap",
    ],
    Pacasmayo: [
        "San Pedro de Lloc",
        "Guadalupe",
        "Jequetepeque",
        "Pacasmayo",
        "San José",
    ],
    Pataz: [
        "Tayabamba",
        "Buldibuyo",
        "Chillia",
        "Huancaspata",
        "Huaylillas",
        "Huayo",
        "Ongon",
        "Parcoy",
        "Pataz",
        "Pias",
        "Santiago de Challas",
        "Taurija",
        "Urpay",
    ],
    "Sánchez Carrión": [
        "Huamachuco",
        "Chugay",
        "Cochorco",
        "Curgos",
        "Marcabal",
        "Sanagorán",
        "Sarin",
        "Sartimbamba",
    ],
    "Santiago de Chuco": [
        "Santiago de Chuco",
        "Angasmarca",
        "Cachicadán",
        "Mollebamba",
        "Mollepata",
        "Quiruvilca",
        "Santa Cruz de Chuca",
        "Santo Domingo de la Capilla",
        "San Isidro",
    ],
    Trujillo: [
        "Trujillo",
        "El Porvenir",
        "Florencia de Mora",
        "Huanchaco",
        "La Esperanza",
        "Laredo",
        "Moche",
        "Poroto",
        "Salaverry",
        "Simbal",
        "Victor Larco Herrera",
    ],
    Virú: ["Virú", "Chao", "Guadalupito"],
    Chiclayo: [
        "Chiclayo",
        "Chongoyape",
        "Eten",
        "Eten Puerto",
        "José Leonardo Ortiz",
        "La Victoria",
        "Lagunas",
        "Monsefú",
        "Nueva Arica",
        "Oyotún",
        "Picsi",
        "Pimentel",
        "Reque",
        "Santa Rosa",
        "Saña",
        "Cayaltí",
        "Patapo",
        "Pomalca",
        "Pucalá",
        "Tuman",
    ],
    Ferreñafe: [
        "Ferreñafe",
        "Cañaris",
        "Incahuasi",
        "Manuel Antonio Mesones Muro",
        "Pítipo",
        "Pueblo Nuevo",
    ],
    Lambayeque: [
        "Lambayeque",
        "Chochope",
        "Illimo",
        "Jayanca",
        "Mochumí",
        "Morrope",
        "Motupe",
        "Olmos",
        "Pacora",
        "Salas",
        "San José",
        "Túcume",
    ],
    Barranca: ["Barranca", "Barranca", "Pativilca", "Supe", "Supe Puerto"],
    Cajatambo: [
        "Cajatambo",
        "Copa",
        "Gorgor",
        "Huancapón",
        "Manás",
        "Cajatambo",
    ],
    Canta: [
        "Canta",
        "Arahuay",
        "Huamantanga",
        "Huaros",
        "Lachaqui",
        "San Buenaventura",
        "Santa Rosa de Quives",
    ],
    Cañete: [
        "San Vicente de Cañete",
        "Asia",
        "Calango",
        "Cerro Azul",
        "Chilca",
        "Coayllo",
        "Imperial",
        "Lunahuaná",
        "Mala",
        "Nuevo Imperial",
        "Pacarán",
        "Quilmaná",
        "San Antonio",
        "San Luis",
        "Santa Cruz de Flores",
        "Zúñiga",
    ],
    Huaral: [
        "Huaral",
        "Atavillos Alto",
        "Atavillos Bajo",
        "Aucallama",
        "Chancay",
        "Ihuari",
        "Lampian",
        "Pacaraos",
        "San Miguel de Acos",
        "Santa Cruz de Andamarca",
        "Sumbilca",
        "Veintisiete de Noviembre",
    ],
    Huarochirí: [
        "Matucana",
        "Antioquía",
        "Callahuanca",
        "Carampoma",
        "Chicla",
        "Cuenca",
        "Huachupampa",
        "Huanza",
        "Huarochirí",
        "Lahuaytambo",
        "Langa",
        "Laraos",
        "Mariatana",
        "Ricardo Palma",
        "San Andrés de Tupicocha",
        "San Antonio",
        "San Bartolomé",
        "San Damian",
        "San Juan de Iris",
        "San Juan de Tantaranche",
        "San Lorenzo de Quinti",
        "San Mateo",
        "San Mateo",
        "San Pedro de Casta",
        "San Pedro de Huancayre",
        "Santa Cruz de Cocachacra",
        "Santa Eulalia",
        "Santiago de Anchucaya",
        "Santiago de Tuna",
        "Santo Domingo de Los Olleros",
        "Surco",
    ],
    Huaura: [
        "Huacho",
        "Ambar",
        "Caleta de Carquín",
        "Checras",
        "Hualmay",
        "Huaura",
        "Leoncio Prado",
        "Paccho",
        "Santa Leonor",
        "Santa María",
        "Sayan",
        "Vegueta",
    ],
    Oyón: [
        "Oyón",
        "Andajes",
        "Caujul",
        "Cochamarca",
        "Naván",
        "Oyón",
        "Pachangara",
    ],
    Yauyos: [
        "Yauyos",
        "Alis",
        "Ayaviri",
        "Azángaro",
        "Cacra",
        "Carania",
        "Catahuasi",
        "Chocos",
        "Cochas",
        "Colonia",
        "Hongos",
        "Huampara",
        "Huancaya",
        "Huangascar",
        "Huantán",
        "Laraos",
        "Lincha",
        "Madean",
        "Miraflores",
        "Omas",
        "Putinza",
        "Quinches",
        "Quinocay",
        "San Joaquín",
        "San Pedro de Pilas",
        "Tanta",
        "Tauripampa",
        "Tomas",
        "Tupe",
        "Viñac",
    ],
    "Alto Amazonas": [
        "Yurimaguas",
        "Balsapuerto",
        "Jeberos",
        "Lagunas",
        "Santa Cruz",
        "Teniente Cesar López Rojas",
    ],
    "Datem del Marañón": [
        "Barranca",
        "Cahuapanas",
        "Manseriche",
        "Morona",
        "Pastaza",
        "Andoas",
    ],
    Loreto: [
        "Maynas",
        "Alto Nanay",
        "Fernando Lores",
        "Indiana",
        "Iquitos",
        "Las Amazonas",
        "Mazán",
        "Napo",
        "Punchana",
        "Putumayo",
        "San Juan Bautista",
        "Tamshiyacu",
        "Teniente Manuel Clavero",
    ],
    "Mariscal Ramón Castilla": [
        "Pebas",
        "Ramo Verde",
        "San Pablo",
        "Yavari",
        "Yavarí",
    ],
    Maynas: [
        "Loreto",
        "Indiana",
        "Iquitos",
        "Las Amazonas",
        "Mazán",
        "Napo",
        "Punchana",
        "Putumayo",
        "San Juan Bautista",
        "Tamshiyacu",
        "Teniente Manuel Clavero",
    ],
    Requena: [
        "Requena",
        "Alto Tapiche",
        "Capelo",
        "Emilio San Martín",
        "Maquia",
        "Puinahua",
        "Saquena",
        "Soplin",
        "Tapiche",
        "Jenaro Herrera",
    ],
    Ucayali: [
        "Contamana",
        "Inahuaya",
        "Padre Márquez",
        "Pampa Hermosa",
        "Sarayacu",
        "Vargas Guerra",
    ],
    Manu: ["Manu", "Fitzcarrald", "Madre de Dios"],
    Tahuamanu: ["Iñapari", "Iberia", "Tahuamanu"],
    Tambopata: ["Tambopata", "Inambari", "Las Piedras", "Laberinto"],
    "General Sánchez Cerro": [
        "Omate",
        "Chojata",
        "Coalaque",
        "Ichuña",
        "La Capilla",
        "Lloque",
        "Matalaque",
        "Puquina",
        "Quinistaquillas",
        "Ubinas",
        "Yunga",
    ],
    Ilo: ["Ilo", "El Algarrobal", "Pacocha"],
    "Mariscal Nieto": [
        "Moquegua",
        "Carumas",
        "Cuchumbaya",
        "Samegua",
        "San Cristóbal",
        "Torata",
    ],
    "Daniel Alcides Carrión": [
        "Yanahuanca",
        "Chacayán",
        "Goyllarisquizga",
        "Paucar",
        "San Pedro de Pillao",
        "Santa Ana de Tusi",
        "Tapuc",
    ],
    Oxapampa: [
        "Oxapampa",
        "Chontabamba",
        "Huancabamba",
        "Palcazu",
        "Pozuzo",
        "Puerto Bermúdez",
        "Villa Rica",
    ],
    Pasco: [
        "Pasco",
        "Chaupimarca",
        "Huachón",
        "Huariaca",
        "Huayllay",
        "Ninacaca",
        "Pallanchacra",
        "Paucartambo",
        "San Francisco de Asís de Yarusyacán",
        "Simón Bolívar",
        "Ticlacayán",
        "Tinyahuarco",
        "Vicco",
        "Yanacancha",
    ],
    Ayabaca: [
        "Ayabaca",
        "Frias",
        "Jilili",
        "Lagunas",
        "Montero",
        "Pacaipampa",
        "Paimas",
        "Sapillica",
        "Sicchez",
        "Suyo",
    ],
    Huancabamba: [
        "Huancabamba",
        "Canchaque",
        "El Carmen de la Frontera",
        "Huarmaca",
        "Lalaquiz",
        "San Miguel de El Faique",
        "Sondor",
        "Sondorillo",
    ],
    Morropón: [
        "Chulucanas",
        "Buenos Aires",
        "Chalaco",
        "La Matanza",
        "Morropón",
        "Salitral",
        "San Juan de Bigote",
        "Santa Catalina de Mossa",
    ],
    Paita: [
        "Paita",
        "Amotape",
        "Arenal",
        "Colán",
        "La Huaca",
        "Tamarindo",
        "Vichayal",
    ],
    Piura: [
        "Piura",
        "Castilla",
        "Catacaos",
        "Cura Mori",
        "El Tallán",
        "La Arena",
        "La Unión",
        "Las Lomas",
        "Tambo Grande",
        "Veintiseis de Octubre",
    ],
    Sechura: [
        "Sechura",
        "Bellavista de la Unión",
        "Bernal",
        "Cristo Nos Valga",
        "Rinconada Llicuar",
        "Vice",
        "Sechura",
    ],
    Sullana: [
        "Sullana",
        "Bellavista",
        "Ignacio Escudero",
        "Lancones",
        "Marcavelica",
        "Miguel Checa",
        "Querecotillo",
        "Salitral",
    ],
    Talara: [
        "Talara",
        "El Alto",
        "La Brea",
        "Lobitos",
        "Los Organos",
        "Mancora",
        "Pariñas",
    ],
    Azángaro: [
        "Azángaro",
        "Achaya",
        "Arapa",
        "Asillo",
        "Caminaca",
        "Chupa",
        "José Domingo Choquehuanca",
        "Muñani",
        "Potoni",
        "Saman",
        "San Anton",
        "San José",
        "San Juan de Salinas",
        "Santiago de Pupuja",
        "Tirapata",
    ],
    Carabaya: [
        "Macusani",
        "Ajoyani",
        "Ayapata",
        "Coasa",
        "Corani",
        "Crucero",
        "Ituata",
        "Ollachea",
        "San Gaban",
        "Usicayos",
    ],
    Chucuito: [
        "Juli",
        "Desaguadero",
        "Huacullani",
        "Kelluyo",
        "Pisacoma",
        "Pomata",
        "Zepita",
    ],
    "El Collao": [
        "Ilave",
        "Capazo",
        "Pilcuyo",
        "Santa Rosa",
        "Conduriri",
        "Huancané",
        "Cojata",
        "Huatasani",
        "Inchupalla",
        "Pusi",
    ],
    Huancané: [
        "Huancané",
        "Huatasani",
        "Inchupalla",
        "Pusi",
        "Rosaspata",
        "Taraco",
        "Vilque Chico",
    ],
    Lampa: [
        "Lampa",
        "Cabanilla",
        "Calapuja",
        "Nicasio",
        "Ocuviri",
        "Palca",
        "Paratia",
        "Pucará",
        "Santa Lucía",
        "Vilavila",
    ],
    Melgar: [
        "Ayaviri",
        "Antauta",
        "Cupi",
        "Llalli",
        "Macari",
        "Nuñoa",
        "Orurillo",
        "Santa Rosa",
        "Umachiri",
    ],
    Moho: ["Moho", "Conima", "Huayrapata", "Tilali"],
    Puno: [
        "Puno",
        "Acora",
        "Amantani",
        "Atuncolla",
        "Capachica",
        "Chucuito",
        "Coata",
        "Huata",
        "Mañazo",
        "Paucarcolla",
        "Pichacani",
        "Plateria",
        "San Antonio",
        "Tiquillaca",
        "Vilque",
    ],
    "San Antonio de Putina": [
        "Putina",
        "Ananea",
        "Pedro Vilca Apaza",
        "Quilcapuncu",
        "Sina",
    ],
    "San Román": ["Juliaca", "Cabana", "Cabanillas", "Caracoto"],
    Sandia: [
        "Sandia",
        "Cuyocuyo",
        "Limbani",
        "Patambuco",
        "Phara",
        "Quiaca",
        "San Juan del Oro",
        "Yanahuaya",
        "Alto Inambari",
        "San Pedro de Putina Punco",
    ],
    Yunguyo: [
        "Yunguyo",
        "Anapia",
        "Copani",
        "Cuturapi",
        "Ollaraya",
        "Tinicachi",
        "Unicachi",
    ],
    Bellavista: [
        "Bellavista",
        "Alto Biavo",
        "Bajo Biavo",
        "Huallaga",
        "San Pablo",
        "San Rafael",
    ],
    "El Dorado": [
        "San José de Sisa",
        "Agua Blanca",
        "San Martín",
        "Santa Rosa",
        "Shatoja",
    ],
    Huallaga: [
        "Saposoa",
        "Alto Saposoa",
        "El Eslabón",
        "Piscoyacu",
        "Sacanche",
        "Tingo de Saposoa",
    ],
    Lamas: [
        "Lamas",
        "Alonso de Alvarado",
        "Barranquita",
        "Caynarachi",
        "Cuñumbuqui",
        "Pinto Recodo",
        "Rumisapa",
        "San Roque de Cumbaza",
        "Shanao",
        "Tabalosos",
        "Zapatero",
    ],
    "Mariscal Cáceres": [
        "Juanjuí",
        "Campanilla",
        "Huicungo",
        "Pachiza",
        "Pajarillo",
    ],
    Moyobamba: [
        "Moyobamba",
        "Calzada",
        "Habana",
        "Jepelacio",
        "Soritor",
        "Yantalo",
    ],
    Picota: [
        "Picota",
        "Buenos Aires",
        "Caspisapa",
        "Pilluana",
        "Pucacaca",
        "San Cristóbal",
        "San Hilarión",
        "Shamboyacu",
        "Tingo de Ponasa",
    ],
    Rioja: [
        "Rioja",
        "Awajún",
        "Elías Soplin Vargas",
        "Nueva Cajamarca",
        "Pardo Miguel",
        "Posic",
        "San Fernando",
        "Yorongos",
    ],
    "San Martín": [
        "Tarapoto",
        "Alberto Leveau",
        "Cacatachi",
        "Chazuta",
        "Chipurana",
        "El Porvenir",
        "Huimbayoc",
        "Juan Guerra",
        "La Banda de Shilcayo",
        "Morales",
        "Papaplaya",
        "San Antonio",
        "Sauce",
        "Shapaja",
    ],
    Tocache: ["Tocache", "Nuevo Progreso", "Polvora", "Shunte", "Uchiza"],
    Candarave: [
        "Candarave",
        "Cairani",
        "Camilaca",
        "Curibaya",
        "Huanuara",
        "Quilahuani",
    ],
    "Jorge Basadre": ["Locumba", "Ilabaya", "Ite"],
    Tacna: [
        "Tacna",
        "Alto de la Alianza",
        "Calana",
        "Ciudad Nueva",
        "Inclán",
        "Pachía",
        "Palca",
        "Pocollay",
        "Sama",
        "Coronel Gregorio Albarracín Lanchipa",
        "La Yarada-Los Palos",
    ],
    Tarata: [
        "Tarata",
        "Héroes Albarracín",
        "Estique",
        "Estique-Pampa",
        "Sitajara",
    ],
    "Contralmirante Villar": ["Zorritos", "Casitas", "Canoas de Punta Sal"],
    Tumbes: [
        "Tumbes",
        "Corrales",
        "La Cruz",
        "Pampas de Hospital",
        "San Jacinto",
        "San Juan de la Virgen",
    ],
    Zarumilla: ["Zarumilla", "Aguas Verdes", "Matapalo", "Papayal"],
    Atalaya: ["Atalaya", "Raymondi", "Sepahua", "Tahuania", "Yurúa"],
    "Coronel Portillo": [
        "Calleria",
        "Campoverde",
        "Iparía",
        "Masisea",
        "Yarinacocha",
    ],
    "Padre Abad": [
        "Padre Abad",
        "Irazola",
        "Curimana",
        "Neshuya",
        "Alexander Von Humboldt",
    ],
    Purús: ["Purús", "Eduardo Villanueva", "Flor de Punga", "Iñapari"],
};

export default dataProvincias;
